/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalframes;

import frames.CashOutFrame;
import java.awt.Color;
import javax.swing.JOptionPane;
import users.Merchant;

/**
 *
 * @author Zahid
 */
public class MerchantHome extends javax.swing.JInternalFrame {

    /**
     * Creates new form merchantHome
     */
    public MerchantHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashOutLabel = new javax.swing.JLabel();
        checkBalanceLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setTitle("Merchant Home - PocketMoney");

        cashOutLabel.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        cashOutLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cashOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_024-purse_3925437.png"))); // NOI18N
        cashOutLabel.setText("   Cash Out");
        cashOutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cashOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashOutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cashOutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cashOutLabelMouseExited(evt);
            }
        });

        checkBalanceLabel.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        checkBalanceLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_013-budget_3925433.png"))); // NOI18N
        checkBalanceLabel.setText("   Check Balance");
        checkBalanceLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkBalanceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBalanceLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkBalanceLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkBalanceLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cashOutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkBalanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(cashOutLabel)
                .addGap(18, 18, 18)
                .addComponent(checkBalanceLabel)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setMerchant(Merchant merchant) {
        curMerchant = merchant;
    }
    
    public Merchant getMerchant() {
        return curMerchant;
    }
    
    private void cashOutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashOutLabelMouseEntered
        cashOutLabel.setForeground(Color.red);
    }//GEN-LAST:event_cashOutLabelMouseEntered

    private void cashOutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashOutLabelMouseExited
        cashOutLabel.setForeground(Color.black);
    }//GEN-LAST:event_cashOutLabelMouseExited

    private void checkBalanceLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBalanceLabelMouseEntered
        checkBalanceLabel.setForeground(Color.red);
    }//GEN-LAST:event_checkBalanceLabelMouseEntered

    private void checkBalanceLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBalanceLabelMouseExited
        checkBalanceLabel.setForeground(Color.black);
    }//GEN-LAST:event_checkBalanceLabelMouseExited

    private void cashOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashOutLabelMouseClicked
        cf.setVisible(true);
    }//GEN-LAST:event_cashOutLabelMouseClicked

    private void checkBalanceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBalanceLabelMouseClicked
        JOptionPane.showMessageDialog(null, "Current balance is Tk. " + getMerchant().getBalance());
    }//GEN-LAST:event_checkBalanceLabelMouseClicked


    private Merchant curMerchant;
    private CashOutFrame cf = new CashOutFrame();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cashOutLabel;
    private javax.swing.JLabel checkBalanceLabel;
    // End of variables declaration//GEN-END:variables
}
