/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalframes;

import javax.swing.ButtonGroup;

/**
 *
 * @author Zahid
 */
public class Report extends javax.swing.JInternalFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        activityRadioButton.setSelected(false);
        transactionRadioButton.setSelected(false);
        topUsersRadioButton.setSelected(false);
        ButtonGroup reportGroup = new ButtonGroup();
        reportGroup.add(activityRadioButton);
        reportGroup.add(transactionRadioButton);
        reportGroup.add(topUsersRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        userTypeLabel = new javax.swing.JLabel();
        customerCheckBox = new javax.swing.JCheckBox();
        agentCheckBox = new javax.swing.JCheckBox();
        merchantCheckBox = new javax.swing.JCheckBox();
        reportDateLabel = new javax.swing.JLabel();
        reportTypeLabel = new javax.swing.JLabel();
        activityRadioButton = new javax.swing.JRadioButton();
        transactionRadioButton = new javax.swing.JRadioButton();
        topUsersRadioButton = new javax.swing.JRadioButton();
        barButton = new javax.swing.JButton();
        pieButton = new javax.swing.JButton();
        lineButton = new javax.swing.JButton();
        tableButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setTitle("Report - PocketMoney");

        userTypeLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userTypeLabel.setText("Select user types: ");

        customerCheckBox.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        customerCheckBox.setText("Customer");

        agentCheckBox.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        agentCheckBox.setText("Agent");

        merchantCheckBox.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        merchantCheckBox.setText("Merchant");

        reportDateLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        reportDateLabel.setText("Enter Report date:");

        reportTypeLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        reportTypeLabel.setText("Select report type: ");

        activityRadioButton.setText("User Activity");

        transactionRadioButton.setText("Transaction Trends");

        topUsersRadioButton.setText("Top Users");

        barButton.setText("Export as Bar Chart");
        barButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barButtonActionPerformed(evt);
            }
        });

        pieButton.setText("Export as Pie Chart");

        lineButton.setText("Export as Line Graph");

        tableButton.setText("Export as Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agentCheckBox)
                    .addComponent(topUsersRadioButton)
                    .addComponent(transactionRadioButton)
                    .addComponent(merchantCheckBox)
                    .addComponent(customerCheckBox)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTypeLabel)
                    .addComponent(reportDateLabel)
                    .addComponent(reportTypeLabel)
                    .addComponent(activityRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(reportDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agentCheckBox)
                    .addComponent(barButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(merchantCheckBox)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activityRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionRadioButton)
                    .addComponent(lineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(topUsersRadioButton)
                .addGap(45, 45, 45)
                .addComponent(tableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activityRadioButton;
    private javax.swing.JCheckBox agentCheckBox;
    private javax.swing.JButton barButton;
    private javax.swing.JCheckBox customerCheckBox;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JButton lineButton;
    private javax.swing.JCheckBox merchantCheckBox;
    private javax.swing.JButton pieButton;
    private javax.swing.JLabel reportDateLabel;
    private javax.swing.JLabel reportTypeLabel;
    private javax.swing.JButton tableButton;
    private javax.swing.JRadioButton topUsersRadioButton;
    private javax.swing.JRadioButton transactionRadioButton;
    private javax.swing.JLabel userTypeLabel;
    // End of variables declaration//GEN-END:variables
}
