/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalframes;

/**
 *
 * @author Zahid
 */
public class Reward extends javax.swing.JInternalFrame {

    /**
     * Creates new form GiveReward
     */
    public Reward() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userListTextArea = new javax.swing.JTextArea();
        rewardAmountLabel = new javax.swing.JLabel();
        rewardAmountText = new javax.swing.JTextField();
        giveRewardButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        selectTxtFileMenuItem = new javax.swing.JMenuItem();
        selectBinFileMenuItem = new javax.swing.JMenuItem();
        optionMenu = new javax.swing.JMenu();
        customerArrayListMenuItem = new javax.swing.JMenuItem();
        agentArraylistMenuItem = new javax.swing.JMenuItem();
        merchantArraylistMenuItem = new javax.swing.JMenuItem();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setTitle("Give Reward - PocketMoney");

        userListTextArea.setEditable(false);
        userListTextArea.setColumns(20);
        userListTextArea.setRows(5);
        jScrollPane1.setViewportView(userListTextArea);

        rewardAmountLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        rewardAmountLabel.setText("Enter reward amount: ");

        rewardAmountText.setToolTipText("");
        rewardAmountText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rewardAmountText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        giveRewardButton.setText("Give Reward ");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(giveRewardButton)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rewardAmountLabel)
                            .addComponent(rewardAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(rewardAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rewardAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(giveRewardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        fileMenu.setText("File");

        selectTxtFileMenuItem.setText("Select .txt file");
        selectTxtFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTxtFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(selectTxtFileMenuItem);

        selectBinFileMenuItem.setText("Select .bin file");
        fileMenu.add(selectBinFileMenuItem);

        menuBar.add(fileMenu);

        optionMenu.setText("Options");

        customerArrayListMenuItem.setText("Select from Customer Arraylist");
        optionMenu.add(customerArrayListMenuItem);

        agentArraylistMenuItem.setText("Select from Agent Arraylist");
        agentArraylistMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentArraylistMenuItemActionPerformed(evt);
            }
        });
        optionMenu.add(agentArraylistMenuItem);

        merchantArraylistMenuItem.setText("Select from Merchant Arraylist");
        optionMenu.add(merchantArraylistMenuItem);

        menuBar.add(optionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectTxtFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTxtFileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTxtFileMenuItemActionPerformed

    private void agentArraylistMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentArraylistMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agentArraylistMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agentArraylistMenuItem;
    private javax.swing.JMenuItem customerArrayListMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton giveRewardButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem merchantArraylistMenuItem;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JPanel panel1;
    private javax.swing.JLabel rewardAmountLabel;
    private javax.swing.JTextField rewardAmountText;
    private javax.swing.JMenuItem selectBinFileMenuItem;
    private javax.swing.JMenuItem selectTxtFileMenuItem;
    private javax.swing.JTextArea userListTextArea;
    // End of variables declaration//GEN-END:variables
}
