/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import users.Customer;

/**
 *
 * @author Zahid
 */
public class CustomerAccountCreateFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerAccountCreateFrame
     */
    public CustomerAccountCreateFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        customerInfo = new ArrayList<Customer>();
    }
    
    private boolean isValidPhoneNo(String phN){
       if(phN.length()==11) {
            if(phN.charAt(0)=='0' && phN.charAt(1)=='1' && phN.charAt(2)=='7') return true;
            else if(phN.charAt(0)=='0' && phN.charAt(1)=='1' && phN.charAt(2)=='3') return true;
            else if(phN.charAt(0)=='0' && phN.charAt(1)=='1' && phN.charAt(2)=='4') return true;
            else if(phN.charAt(0)=='0' && phN.charAt(1)=='1' && phN.charAt(2)=='5') return true;
            else if(phN.charAt(0)=='0' && phN.charAt(1)=='1' && phN.charAt(2)=='6') return true;
            else if(phN.charAt(0)=='0' && phN.charAt(1)=='1' && phN.charAt(2)=='8') return true;
            else if(phN.charAt(0)=='0' && phN.charAt(1)=='1' && phN.charAt(2)=='9') return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberText = new javax.swing.JTextField();
        pinLabel = new javax.swing.JLabel();
        pinText = new javax.swing.JTextField();
        createAccountLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        balanceText = new javax.swing.JTextField();
        limitLabel = new javax.swing.JLabel();
        limitText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Customer account - PocketMoney");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        backgroundPanel.setBackground(new java.awt.Color(250, 250, 250));

        backLabel.setFont(new java.awt.Font("Gadugi", 1, 11)); // NOI18N
        backLabel.setIcon(new javax.swing.ImageIcon("D:\\PocketMoney\\src\\images\\if_Rewind_2001873.png")); // NOI18N
        backLabel.setText("Back");
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLabelMouseExited(evt);
            }
        });

        phoneNumberLabel.setFont(new java.awt.Font("Gadugi", 1, 11)); // NOI18N
        phoneNumberLabel.setText("Enter phone number: ");

        pinLabel.setFont(new java.awt.Font("Gadugi", 1, 11)); // NOI18N
        pinLabel.setText("Enter desired PIN code (must be 6-digits): ");

        createAccountLabel.setFont(new java.awt.Font("Gadugi", 1, 11)); // NOI18N
        createAccountLabel.setIcon(new javax.swing.ImageIcon("D:\\PocketMoney\\src\\images\\if_free-29_618316.png")); // NOI18N
        createAccountLabel.setText("Create Account");
        createAccountLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createAccountLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createAccountLabelMouseExited(evt);
            }
        });

        balanceLabel.setFont(new java.awt.Font("Gadugi", 1, 11)); // NOI18N
        balanceLabel.setText("Enter Initial balance (Format: 0.0): ");

        limitLabel.setFont(new java.awt.Font("Gadugi", 1, 11)); // NOI18N
        limitLabel.setText("Enter Limit (Format: 0.0): ");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backLabel))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createAccountLabel)
                            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(balanceLabel)
                                    .addComponent(phoneNumberLabel)
                                    .addComponent(phoneNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(pinLabel)
                                    .addComponent(pinText)
                                    .addComponent(balanceText))
                                .addComponent(limitLabel)
                                .addComponent(limitText, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLabel)
                .addGap(40, 40, 40)
                .addComponent(phoneNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pinLabel)
                .addGap(8, 8, 8)
                .addComponent(pinText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(balanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(limitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limitText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createAccountLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    private void backLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseEntered
        backLabel.setForeground(Color.blue);
    }//GEN-LAST:event_backLabelMouseEntered

    private void backLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseExited
        backLabel.setForeground(Color.black);
    }//GEN-LAST:event_backLabelMouseExited

    private void createAccountLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountLabelMouseEntered
        createAccountLabel.setForeground(Color.blue);
    }//GEN-LAST:event_createAccountLabelMouseEntered

    private void createAccountLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountLabelMouseExited
        createAccountLabel.setForeground(Color.black);
    }//GEN-LAST:event_createAccountLabelMouseExited

    private void createAccountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountLabelMouseClicked
        if(isValidPhoneNo(phoneNumberText.getText())==true) {
            Customer c = new Customer(
                        phoneNumberText.getText(),
                        "Customer",
                        pinText.getText(),
                        Float.parseFloat(balanceText.getText()),
                        Float.parseFloat(limitText.getText())
            );
                c.setId(phoneNumberText.getText());
                c.setType("Customer");
                c.setPin(pinText.getText());
                c.setBalance(Float.parseFloat(balanceText.getText()));
                c.setLimit(Float.parseFloat(limitText.getText()));
                customerInfo.add(c);
                //u.addCustomer(c);
                boolean append = true;
                try {
                    ObjectOutputStream out = null;
                    File file = new File("customerInfo.bin");
                    if(!file.exists() || !append) {
                        out = new ObjectOutputStream(new FileOutputStream(file));
                    }
                    else {
                        out = new AppendableObjectOutputStream(new FileOutputStream(file, append));
                    }
                    for(Customer customer: customerInfo)
                        out.writeObject(customer);
                    out.close();
                } catch(Exception e) {}
                this.dispose();
                JOptionPane.showMessageDialog(null,"Account Created!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Phone number invalid! Try again.");
        }
    }//GEN-LAST:event_createAccountLabelMouseClicked

    /**
     * @param args the command line arguments
     */

    private ArrayList<Customer> customerInfo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JTextField balanceText;
    private javax.swing.JLabel createAccountLabel;
    private javax.swing.JLabel limitLabel;
    private javax.swing.JTextField limitText;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberText;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JTextField pinText;
    // End of variables declaration//GEN-END:variables
}
