/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import internalframes.MerchantHome;
import internalframes.MerchantLimit;
import internalframes.Statement;
import java.awt.Color;

/**
 *
 * @author Zahid
 */
public class MerchantFrame extends javax.swing.JFrame {

    /**
     * Creates new form MerchantFrame
     */
    public MerchantFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        seperator1 = new javax.swing.JPanel();
        merchantLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        statementLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        limitsLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        logoutLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signed in as Merchant - PocketMoney");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        seperator1.setBackground(new java.awt.Color(250, 250, 250));
        seperator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        seperator1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seperator1MouseEntered(evt);
            }
        });

        merchantLabel.setBackground(new java.awt.Color(0, 153, 255));
        merchantLabel.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        merchantLabel.setForeground(new java.awt.Color(255, 255, 255));
        merchantLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        merchantLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_profle_1055000.png"))); // NOI18N
        merchantLabel.setText(" Merchant");
        merchantLabel.setOpaque(true);

        homeLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Streamline-18_185038.png"))); // NOI18N
        homeLabel.setText(" Home");
        homeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLabelMouseExited(evt);
            }
        });

        statementLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        statementLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statementLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_icon-62-document-table_314903.png"))); // NOI18N
        statementLabel.setText("Statement");
        statementLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statementLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statementLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statementLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statementLabelMouseExited(evt);
            }
        });

        limitsLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        limitsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limitsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_icon-61-warning_315935.png"))); // NOI18N
        limitsLabel.setText("Limits");
        limitsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limitsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limitsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limitsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limitsLabelMouseExited(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Gadugi", 1, 11)); // NOI18N
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_logout_54231.png"))); // NOI18N
        logoutLabel.setText("Log Out");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout seperator1Layout = new javax.swing.GroupLayout(seperator1);
        seperator1.setLayout(seperator1Layout);
        seperator1Layout.setHorizontalGroup(
            seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(merchantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seperator1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addGap(46, 46, 46))
            .addGroup(seperator1Layout.createSequentialGroup()
                .addGroup(seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
        );
        seperator1Layout.setVerticalGroup(
            seperator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seperator1Layout.createSequentialGroup()
                .addComponent(merchantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeLabel)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(statementLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limitsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
            .addComponent(seperator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseEntered
        homeLabel.setForeground(Color.blue);
    }//GEN-LAST:event_homeLabelMouseEntered

    private void homeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseExited
        homeLabel.setForeground(Color.black);
    }//GEN-LAST:event_homeLabelMouseExited

    private void statementLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementLabelMouseEntered
        statementLabel.setForeground(Color.blue);
    }//GEN-LAST:event_statementLabelMouseEntered

    private void statementLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementLabelMouseExited
        statementLabel.setForeground(Color.black);
    }//GEN-LAST:event_statementLabelMouseExited

    private void limitsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limitsLabelMouseEntered
        limitsLabel.setForeground(Color.blue);
    }//GEN-LAST:event_limitsLabelMouseEntered

    private void limitsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limitsLabelMouseExited
        limitsLabel.setForeground(Color.black);
    }//GEN-LAST:event_limitsLabelMouseExited

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        logoutLabel.setForeground(Color.red);
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        logoutLabel.setForeground(Color.black);
    }//GEN-LAST:event_logoutLabelMouseExited

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        desktopPane.removeAll();
        desktopPane.add(mh);
        mh.setVisible(true);
        desktopPane.validate();
    }//GEN-LAST:event_homeLabelMouseClicked

    private void statementLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statementLabelMouseClicked
        desktopPane.removeAll();
        desktopPane.add(st);
        st.setVisible(true);
        desktopPane.validate();
    }//GEN-LAST:event_statementLabelMouseClicked

    private void limitsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limitsLabelMouseClicked
        desktopPane.removeAll();
        desktopPane.add(ml);
        ml.setVisible(true);
        desktopPane.validate();
    }//GEN-LAST:event_limitsLabelMouseClicked

    private void seperator1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seperator1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_seperator1MouseEntered

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        this.dispose();
        l.setVisible(true);
    }//GEN-LAST:event_logoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MerchantFrame().setVisible(true);
            }
        });
    }
    
    private MerchantHome mh = new MerchantHome();
    private Statement st = new Statement();
    private MerchantLimit ml = new MerchantLimit();
    private Login l = new Login();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel limitsLabel;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel merchantLabel;
    private javax.swing.JPanel seperator1;
    private javax.swing.JLabel statementLabel;
    // End of variables declaration//GEN-END:variables
}
