/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import javax.swing.JOptionPane;
import users.Customer;

/**
 *
 * @author Zahid
 */
public class MobileRechargeFrame extends javax.swing.JFrame {

    /**
     * Creates new form MobileRechargeFrame
     */
    public MobileRechargeFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    public void setCustomer(Customer customer){
        curCustomer = customer;
    }
    
    public Customer getCustomer(){
        return curCustomer;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        recipientCellLabel = new javax.swing.JLabel();
        recipientCellText = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        rechargeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        backgroundPanel.setBackground(new java.awt.Color(250, 250, 250));

        recipientCellLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        recipientCellLabel.setText("Enter Recipient phone number: ");

        recipientCellText.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N

        amountLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        amountLabel.setText("Enter Amount: ");

        rechargeLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        rechargeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Tick_Mark_Dark_1398912.png"))); // NOI18N
        rechargeLabel.setText("Recharge");
        rechargeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rechargeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechargeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rechargeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rechargeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rechargeLabel)
                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(recipientCellLabel)
                        .addComponent(recipientCellText)
                        .addComponent(amountLabel)
                        .addComponent(amountText, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(recipientCellLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recipientCellText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rechargeLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechargeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechargeLabelMouseEntered
        rechargeLabel.setForeground(Color.green);
    }//GEN-LAST:event_rechargeLabelMouseEntered

    private void rechargeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechargeLabelMouseExited
        rechargeLabel.setForeground(Color.black);
    }//GEN-LAST:event_rechargeLabelMouseExited

    private void rechargeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechargeLabelMouseClicked
        float balance = Float.parseFloat(amountText.getText());
        getCustomer().mobileRecharge(curCustomer, recipientCellText.getText(), balance);
        this.dispose();
        JOptionPane.showMessageDialog(null, "Mobile Recharge completed!");
    }//GEN-LAST:event_rechargeLabelMouseClicked

    /**
     * @param args the command line arguments
     */

    private Customer curCustomer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountText;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel rechargeLabel;
    private javax.swing.JLabel recipientCellLabel;
    private javax.swing.JTextField recipientCellText;
    // End of variables declaration//GEN-END:variables
}
