/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Zahid
 */
public class PaymentFrame extends javax.swing.JFrame {

    /**
     * Creates new form PaymentFrame
     */
    public PaymentFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        utilityBillRadioButton.setSelected(true);
        paymentRadioButton.setSelected(false);
        ButtonGroup paymentGroup = new ButtonGroup();
        paymentGroup.add(utilityBillRadioButton);
        paymentGroup.add(paymentRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        paymentRadioButton = new javax.swing.JRadioButton();
        utilityBillRadioButton = new javax.swing.JRadioButton();
        panel1 = new javax.swing.JPanel();
        utilityBillTypeComboBox = new javax.swing.JComboBox<>();
        proceedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        backgroundPanel.setBackground(new java.awt.Color(250, 250, 250));

        paymentRadioButton.setText("Payment");
        paymentRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentRadioButtonActionPerformed(evt);
            }
        });

        utilityBillRadioButton.setText("Utility Bill");
        utilityBillRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        utilityBillRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilityBillRadioButtonActionPerformed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(250, 250, 250));

        utilityBillTypeComboBox.setBackground(new java.awt.Color(250, 250, 250));
        utilityBillTypeComboBox.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        utilityBillTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--None--", "Electricity", "Water", "Gas" }));
        utilityBillTypeComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utilityBillTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(utilityBillTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        proceedLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        proceedLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Tick_Mark_Dark_1398912.png"))); // NOI18N
        proceedLabel.setText("Proceed to Payment");
        proceedLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proceedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proceedLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proceedLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proceedLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(paymentRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(utilityBillRadioButton)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proceedLabel)
                .addGap(34, 34, 34))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentRadioButton)
                    .addComponent(utilityBillRadioButton))
                .addGap(18, 18, 18)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(proceedLabel)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void utilityBillRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilityBillRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilityBillRadioButtonActionPerformed

    private void proceedLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedLabelMouseEntered
        proceedLabel.setForeground(Color.green);
    }//GEN-LAST:event_proceedLabelMouseEntered

    private void proceedLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedLabelMouseExited
        proceedLabel.setForeground(Color.black);
    }//GEN-LAST:event_proceedLabelMouseExited

    private void proceedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedLabelMouseClicked
        if(utilityBillTypeComboBox.getSelectedItem() != "--None--" ) {
            this.dispose();
            PaymentAmountFrame pa = new PaymentAmountFrame();
            pa.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Error! Please select a bill type.");
        }
    }//GEN-LAST:event_proceedLabelMouseClicked

    private void paymentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentRadioButtonActionPerformed
        this.dispose();
        QrCodeScanner qr = new QrCodeScanner();
        qr.setVisible(true);
    }//GEN-LAST:event_paymentRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel panel1;
    private javax.swing.JRadioButton paymentRadioButton;
    private javax.swing.JLabel proceedLabel;
    private javax.swing.JRadioButton utilityBillRadioButton;
    private javax.swing.JComboBox<String> utilityBillTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
