/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;

/**
 *
 * @author Zahid
 */
public class QrCodeScanner extends javax.swing.JFrame {

    /**
     * Creates new form QrCodeScanner
     */
    public QrCodeScanner() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        qrLabel = new javax.swing.JLabel();
        scanLabel = new javax.swing.JLabel();
        merchantIdLabel = new javax.swing.JLabel();
        merchantIdText = new javax.swing.JTextField();
        proceedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Scan QR Code - PocketMoney");
        setType(java.awt.Window.Type.UTILITY);

        backgroundPanel.setBackground(new java.awt.Color(250, 250, 250));

        qrLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qr-code.png"))); // NOI18N

        scanLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        scanLabel.setText("Scan QR Code");

        merchantIdLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        merchantIdLabel.setText("Or, Enter Merchant ID: ");

        proceedLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        proceedLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Tick_Mark_Dark_1398912.png"))); // NOI18N
        proceedLabel.setText("Proceed to payment");
        proceedLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proceedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proceedLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                proceedLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                proceedLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scanLabel)
                .addGap(162, 162, 162))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(proceedLabel)
                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(merchantIdLabel)
                        .addComponent(qrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(merchantIdText)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(qrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(merchantIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(merchantIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proceedLabel)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proceedLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedLabelMouseEntered
        proceedLabel.setForeground(Color.green);
    }//GEN-LAST:event_proceedLabelMouseEntered

    private void proceedLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedLabelMouseExited
        proceedLabel.setForeground(Color.black);
    }//GEN-LAST:event_proceedLabelMouseExited

    private void proceedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedLabelMouseClicked
        this.dispose();
        PaymentAmountFrame pa = new PaymentAmountFrame();
        pa.setVisible(true);
    }//GEN-LAST:event_proceedLabelMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel merchantIdLabel;
    private javax.swing.JTextField merchantIdText;
    private javax.swing.JLabel proceedLabel;
    private javax.swing.JLabel qrLabel;
    private javax.swing.JLabel scanLabel;
    // End of variables declaration//GEN-END:variables
}
