/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author Zahid
 */
public class SendMoneyFrame extends javax.swing.JFrame {

    /**
     * Creates new form SendMoneyFrame
     */
    public SendMoneyFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        recipientIdLabel = new javax.swing.JLabel();
        recipientIdText = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        sendMoneyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setType(java.awt.Window.Type.UTILITY);

        backgroundPanel.setBackground(new java.awt.Color(250, 250, 250));

        backLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_Rewind_2001873.png"))); // NOI18N
        backLabel.setText("Back");

        recipientIdLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        recipientIdLabel.setText("Enter Recipient ID: ");

        recipientIdText.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N

        amountLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        amountLabel.setText("Enter Amount: ");

        sendMoneyLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        sendMoneyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Tick_Mark_Dark_1398912.png"))); // NOI18N
        sendMoneyLabel.setText("Send Money");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backLabel))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sendMoneyLabel)
                            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(recipientIdLabel)
                                .addComponent(recipientIdText)
                                .addComponent(amountLabel)
                                .addComponent(amountText, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLabel)
                .addGap(18, 18, 18)
                .addComponent(recipientIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recipientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendMoneyLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountText;
    private javax.swing.JLabel backLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel recipientIdLabel;
    private javax.swing.JTextField recipientIdText;
    private javax.swing.JLabel sendMoneyLabel;
    // End of variables declaration//GEN-END:variables
}
