/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import users.Customer;

/**
 *
 * @author Zahid
 */
public class SendMoneyFrame extends javax.swing.JFrame {

    /**
     * Creates new form SendMoneyFrame
     */
    public SendMoneyFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setCustomer(Customer customer) {
        curCustomer = customer;
    }
    
    public Customer getCustomer() {
        return curCustomer;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        recipientIdLabel = new javax.swing.JLabel();
        recipientIdText = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        sendMoneyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setType(java.awt.Window.Type.UTILITY);

        backgroundPanel.setBackground(new java.awt.Color(250, 250, 250));

        recipientIdLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        recipientIdLabel.setText("Enter Recipient ID: ");

        recipientIdText.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N

        amountLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        amountLabel.setText("Enter Amount: ");

        sendMoneyLabel.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        sendMoneyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Tick_Mark_Dark_1398912.png"))); // NOI18N
        sendMoneyLabel.setText("Send Money");
        sendMoneyLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendMoneyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMoneyLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMoneyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendMoneyLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendMoneyLabel)
                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(recipientIdLabel)
                        .addComponent(recipientIdText)
                        .addComponent(amountLabel)
                        .addComponent(amountText, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(recipientIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recipientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendMoneyLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMoneyLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMoneyLabelMouseEntered
        sendMoneyLabel.setForeground(Color.green);
    }//GEN-LAST:event_sendMoneyLabelMouseEntered

    private void sendMoneyLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMoneyLabelMouseExited
        sendMoneyLabel.setForeground(Color.black);
    }//GEN-LAST:event_sendMoneyLabelMouseExited

    private void sendMoneyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMoneyLabelMouseClicked
        String recipient = recipientIdText.getText();
        float amount = Float.parseFloat(amountText.getText());
        try {
            Customer c = getCustomer();
            c.sendMoney(recipient, amount);
            recipientIdText.setText("");
            amountText.setText("");
            this.dispose();
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_sendMoneyLabelMouseClicked

    /**
     * @param args the command line arguments
     */

    private Customer curCustomer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountText;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel recipientIdLabel;
    private javax.swing.JTextField recipientIdText;
    private javax.swing.JLabel sendMoneyLabel;
    // End of variables declaration//GEN-END:variables
}
